build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
    dependencies:
        override:
            - composer install --no-interaction

tools:
    external_code_coverage:
        timeout: 3600

filter:
    excluded_paths:
        - vendor