sudo: false
language: php

php:
    - 7.4
    
before_script:
    - composer self-update
    - composer install --no-interaction
    
script:
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse
    - vendor/bin/psalm --show-info=false
    - vendor/bin/ecs check src tests
    
after_script:
    - vendor/bin/phpunit --coverage-clover data/test-coverage/clover/clover.xml


after_success:
  - travis_retry vendor/bin/php-coveralls